using System;
using System.Collections.Generic;
using System.Text;

namespace CoffeeCore.DTO
{
    public class ChartInputAdvancedDTO
    {
        public Double LGerminationSeedCollection { get; set; }
        public Double LGerminationSeedSelection { get; set; }
        public Double LGerminationNurseryConstruction { get; set; }
        public Double LGerminationSeedingSupportIrrigation { get; set; }
        public Double LGerminationOthers { get; set; }
        public Double LNurseryConstruction { get; set; }
        public Double LNurseryDrawnPulled { get; set; }
        public Double LNurseryClean { get; set; }
        public Double LNurserySoilPreparationFertilizer { get; set; }
        public Double LNurseryFilledLockedBags { get; set; }
        public Double LNurseryButterflySowing { get; set; }
        public Double LNurseryIrrigation { get; set; }
        public Double LNurseryFoliarApplication { get; set; }
        public Double LNurseryReseeding { get; set; }
        public Double LNurseryOthers { get; set; }
        public Double LPPFieldCleaning { get; set; }
        public Double LPPCuttingTrees { get; set; }
        public Double LPPWoodCollection { get; set; }
        public Double LPPWoodChopping { get; set; }
        public Double LPPCoffeeLayout { get; set; }
        public Double LPPHoleDigging { get; set; }
        public Double LPPSeedlingTransportation { get; set; }
        public Double LPPSeedlingTransplant { get; set; }
        public Double LPPShadeAdjustment { get; set; }
        public Double LPPCompostMixing { get; set; }
        public Double LPPOthers { get; set; }
        public Double LPPYWeeding { get; set; }
        public Double LPPYOrganic { get; set; }
        public Double LPPYChemical { get; set; }
        public Double LPPYFoliarSpraying { get; set; }
        public Double LPPYOther { get; set; }
        public Double LHPMYManualWeeding { get; set; }
        public Double LHPMYChemicalWeeding { get; set; }
        public Double LHPMYOrganicFertilizers { get; set; }
        public Double LHPMYChemicalFertilizers { get; set; }
        public Double LHPMYFoliarSpraying { get; set; }
        public Double LHPMYHedgerowsConstruction { get; set; }
        public Double LHPMYShadetreePruning { get; set; }
        public Double LHPMYPestControl { get; set; }
        public Double LHPMYCoffeeGrowManagement { get; set; }
        public Double LHPMYOthers { get; set; }
        public Double LHPHYCoffeeCollecDays { get; set; }
        public Double LHPHYAdditionDays { get; set; }
        public Double LHPPYFermentation { get; set; }
        public Double LHPPYWashing { get; set; }
        public Double LHPPYDrying { get; set; }
        public Double LHPPYScreening { get; set; }
        public Double LHPPYSelection { get; set; }
        public Double LHPPYStorage { get; set; }
        public Double LHPPYCoffeewastewater { get; set; }
        public Double LHPPYPulpManagement { get; set; }
        public Double LHPPYOthers { get; set; }
        public Double LHPMMManualWeeding { get; set; }
        public Double LHPMMChemicalWeeding { get; set; }
        public Double LHPMMOrganicFertilizers { get; set; }
        public Double LHPMMChemicalFertilizers { get; set; }
        public Double LHPMMFoliarSpraying { get; set; }
        public Double LHPMMHedgerowsConstruction { get; set; }
        public Double LHPMMShadetreePruning { get; set; }
        public Double LHPMMPestControl { get; set; }
        public Double LHPMMCoffeeGrowManagement { get; set; }
        public Double LHPMMOthers { get; set; }
        public Double LHPHMCoffeeCollecDays { get; set; }
        public Double LHPHMAdditionDays { get; set; }
        public Double LHPPMFermentation { get; set; }
        public Double LHPPMWashing { get; set; }
        public Double LHPPMDrying { get; set; }
        public Double LHPPMScreening { get; set; }
        public Double LHPPMSelection { get; set; }
        public Double LHPPMStorage { get; set; }
        public Double LHPPMCoffeewastewater { get; set; }
        public Double LHPPMPulpManagement { get; set; }
        public Double LHPPMOthers { get; set; }
        public Double LHPMOManualWeeding { get; set; }
        public Double LHPMOChemicalWeeding { get; set; }
        public Double LHPMOOrganicFertilizers { get; set; }
        public Double LHPMOChemicalFertilizers { get; set; }
        public Double LHPMOFoliarSpraying { get; set; }
        public Double LHPMOHedgerowsConstruction { get; set; }
        public Double LHPMOShadetreePruning { get; set; }
        public Double LHPMOPestControl { get; set; }
        public Double LHPMOCoffeeGrowManagement { get; set; }
        public Double LHPMOOthers { get; set; }
        public Double LHPHOCoffeeCollecDays { get; set; }
        public Double LHPHOAdditionDays { get; set; }
        public Double LHPPOFermentation { get; set; }
        public Double LHPPOWashing { get; set; }
        public Double LHPPODrying { get; set; }
        public Double LHPPOScreening { get; set; }
        public Double LHPPOSelection { get; set; }
        public Double LHPPOStorage { get; set; }
        public Double LHPPOCoffeewastewater { get; set; }
        public Double LHPPOPulpManagement { get; set; }
        public Double LHPPOOthers { get; set; }
        public Double IIFood { get; set; }
        public Double IIAdditionalTransfers { get; set; }
        public Double IIDaysoftraining { get; set; }
        public Double ICCreditfromcooperative { get; set; }
        public Double ICCreditfromcooperativeTime { get; set; }
        public Double ICCreditfromcooperativeInterest { get; set; }
        public Double ICCreditfromagent { get; set; }
        public Double ICCreditfromagentTime { get; set; }
        public Double ICCreditfromagentInterest { get; set; }
        public Double CostGerminator { get; set; }
        public Double CostGerminatorSeeds { get; set; }
        public Double CostGerminatorSeedbed { get; set; }
        public Double CostGerminatorSandSubstrate { get; set; }
        public Double CostGerminatorCalciumSulfide { get; set; }
        public Double CostGerminatorLime { get; set; }
        public Double CostGerminatorPlastic { get; set; }
        public Double CostGerminatorOthers { get; set; }
        public Double CostNurseryFertilizer { get; set; }
        public Double CostNurseryPlasticBags { get; set; }
        public Double CostNurseryNetting { get; set; }
        public Double CostNurseryStuds { get; set; }
        public Double CostNurseryWire { get; set; }
        public Double CostNurseryCiclonics { get; set; }
        public Double CostNurseryStaples { get; set; }
        public Double CostNurserySoil { get; set; }
        public Double CostNurseryBioFert { get; set; }
        public Double CostNurseryAgroChemicals { get; set; }
        public Double CostNurseryFungicide { get; set; }
        public Double CostNurseryPhosphoricRock { get; set; }
        public Double CostNurseryOthers { get; set; }
        public Double CostFLPPOrganicFert { get; set; }
        public Double CostFLPPChemicalFert { get; set; }
        public Double CostFVGOrganicFert { get; set; }
        public Double CostFVGChemicalFert { get; set; }
        public Double CostFMOtherFert { get; set; }
        public Double CostFMOrganicFoliar { get; set; }
        public Double CostFMChemicalFoliar { get; set; }
        public Double CostFMGasFuel { get; set; }
        public Double CostFMOthers { get; set; }
        public Double EGEManualSprayer { get; set; }
        public Double EGELifespam1 { get; set; }
        public Double EGEMachetes { get; set; }
        public Double EGELifespam2 { get; set; }
        public Double EGEShovel { get; set; }
        public Double EGELifespam3 { get; set; }
        public Double EGEHoe { get; set; }
        public Double EGELifespam4 { get; set; }
        public Double EGEWheelBarrow { get; set; }
        public Double EGELifespam5 { get; set; }
        public Double EGELime { get; set; }
        public Double EGELifespam6 { get; set; }
        public Double EGEAuger { get; set; }
        public Double EGELifespam7 { get; set; }
        public Double EGEMetalBar { get; set; }
        public Double EGELifespam8 { get; set; }
        public Double EGEHose { get; set; }
        public Double EGELifespam9 { get; set; }
        public Double EGESprinklers { get; set; }
        public Double EGELifespam10 { get; set; }
        public Double EGEChainSaw { get; set; }
        public Double EGELifespam11 { get; set; }
        public Double EGEHandSaw { get; set; }
        public Double EGELifespam12 { get; set; }
        public Double EGEMotorPump { get; set; }
        public Double EGELifespam13 { get; set; }
        public Double EGEPrunningScissors { get; set; }
        public Double EGELifespam14 { get; set; }
        public Double EGEAxe { get; set; }
        public Double EGELifespam15 { get; set; }
        public Double EEHScale { get; set; }
        public Double EEHLifespam1 { get; set; }
        public Double EEHVehicle { get; set; }
        public Double EEHLifespam2 { get; set; }
        public Double EEHWorkAnimal { get; set; }
        public Double EEHLifespam3 { get; set; }
        public Double EEHMotorcycle { get; set; }
        public Double EEHLifespam4 { get; set; }
        public Double EEHBags { get; set; }
        public Double EEHLifespam5 { get; set; }
        public Double EEHSack { get; set; }
        public Double EEHLifespam6 { get; set; }
        public Double EEHStraw { get; set; }
        public Double EEHLifespam7 { get; set; }
        public Double EEHBaskets { get; set; }
        public Double EEHLifespam8 { get; set; }
        public Double EEHBoxes { get; set; }
        public Double EEHLifespam9 { get; set; }
        public Double EEHOthers { get; set; }
        public Double EEHLifespam10 { get; set; }
        public Double EEPPulperMachine { get; set; }
        public Double EEPLifespam1 { get; set; }
        public Double EEPTolca { get; set; }
        public Double EEPLifespam2 { get; set; }
        public Double EEPEngine { get; set; }
        public Double EEPLifespam3 { get; set; }
        public Double EEPTanks { get; set; }
        public Double EEPLifespam4 { get; set; }
        public Double EEPWaterChannel { get; set; }
        public Double EEPLifespam5 { get; set; }
        public Double EEPPVCPipes { get; set; }
        public Double EEPLifespam6 { get; set; }
        public Double EEPFilteringSystem { get; set; }
        public Double EEPLifespam7 { get; set; }
        public Double EEPScreeningMachine { get; set; }
        public Double EEPLifespam8 { get; set; }
        public Double EEPDesmucilaginador { get; set; }
        public Double EEPLifespam9 { get; set; }
        public Double EEPMotorPump { get; set; }
        public Double EEPLifespam10 { get; set; }
        public Double EEPOthersWetInput { get; set; }
        public Double EEPLifespam11 { get; set; }
        public Double EEPConcrete { get; set; }
        public Double EEPLifespam12 { get; set; }
        public Double EEPPlastic { get; set; }
        public Double EEPLifespam13 { get; set; }
        public Double EEPRake { get; set; }
        public Double EEPLifespam14 { get; set; }
        public Double EEPBroom { get; set; }
        public Double EEPLifespam15 { get; set; }
        public Double EEPStorageRoom { get; set; }
        public Double EEPLifespam16 { get; set; }
        public Double EEPOthersDryInput { get; set; }
        public Double EEPLifespam17 { get; set; }
        public Double ACCApplicationFee { get; set; }
        public Double ACCAnnualMembership { get; set; }
        public Double ACCLifeInsurance { get; set; }
        public Double ACCFLOCertification { get; set; }
        public Double ACCOrganicCertification { get; set; }
        public Double ACLLandValue { get; set; }
        public Double ACLPropertyTax { get; set; }
        public Double ACUSuperviseInvest { get; set; }
        public Double ACUAdministInvest { get; set; }
        public Double ACUTrainingInvest { get; set; }
        public Double ACUExtraOrdInvest { get; set; }
        public Double TGSeedPurchase { get; set; }
        public Double TGWoodTransportation { get; set; }
        public Double TGSandTransportation { get; set; }
        public Double TGOthers { get; set; }
        public Double TNSoilTransportation { get; set; }
        public Double TNSacksMaterialShopping { get; set; }
        public Double TNOthers { get; set; }
        public Double TLPWoodTransportation { get; set; }
        public Double TLPCompostTransportation { get; set; }
        public Double TLPPlantTransportation { get; set; }
        public Double TLPOthers { get; set; }
        public Double TOtherEquipment { get; set; }
        public Double TOtherLaborTransportation { get; set; }
        public Double TOtherCoffeeTransportation { get; set; }
        public Double TOtherSupervisingActivities { get; set; }
        public Double TOthers { get; set; }
    }
}
